service: aws-deploy-simple-model

provider:
  name: aws
  region: us-west-2

functions:
  huggingface:
    image: 194847020626.dkr.ecr.us-west-2.amazonaws.com/aws-deploy-simple-model@sha256:fba0fce392c8549088907c2dd249e80e06122e8dbca38b5b8cafaf88b0be767e
    # 2 minutes before we throw a timeout
    timeout: 120
    # have 1 hot lambda available
    provisionedConcurrency: 0
    # our model is less than 1GB, so 1024MB is enough
    memorySize: 1024 
    events:
      - http:
          path: prediction
          method: post