service: aws-deploy-simple-model

provider:
  name: aws
  region: us-west-2

functions:
  huggingface:
    image: 194847020626.dkr.ecr.us-west-2.amazonaws.com/aws-deploy-simple-model@sha256:7524bf535e67b7944c6d24db804ed79c031c1cc5fd3defd7d3411a178e1d1b56
    # 2 minutes before we throw a timeout
    timeout: 120
    # have 1 hot lambda available
    provisionedConcurrency: 0
    # our model is less than 1GB, so 1024MB is enough
    memorySize: 1024 
    events:
      - http:
          path: prediction
          method: post